In [1]:
import re
import pandas as pd

In [ ]:
file = open("./WS-Chat.txt", "r", encoding="utf-8")
data = file.read()
print(data)

In [3]:
# Re expression to get only msg, and remove time and date
# i.e: "26/12/2000, 12:00 - "
pattern = '\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s-\s'
# pattern='\d{1,2}\/\d{1,2}\/\d{2},\s\d{1,2}:\d{2}\s(?:AM|PM)'  #This Pattern fo rAM/PM timing

In [4]:
message = re.split(pattern, data, flags=re.I)[1:]
print(message)

['Messages and calls are end-to-end encrypted. No one outside of this chat, not even WhatsApp, can read or listen to them. Tap to learn more.\n', 'FHWS Aniket 🇩🇪: Hi\n', 'FHWS Aniket 🇩🇪: Aniket here\n', 'FHWS Aniket 🇩🇪: Did you book an appointment at consulate or visa application centre\n', 'FHWS Aniket 🇩🇪: Whtas your name and where are you from?\n', 'FHWS Aniket 🇩🇪: *whats\n', 'Dhruval Bhuva: At vfs\n', 'Dhruval Bhuva: Dhruval\nFrom Gujarat\n', 'Dhruval Bhuva: Where do you have\n', 'FHWS Aniket 🇩🇪: Mumbai Visa application centre\n', 'FHWS Aniket 🇩🇪: On Monday\n', 'FHWS Aniket 🇩🇪: I am Aniket from Pune\n', 'FHWS Aniket 🇩🇪: Did you enquire about 30 ECTS?\n', 'FHWS Aniket 🇩🇪: Paid fees and enrolled?\n', 'Dhruval Bhuva: Urmi Axis Building, 3rd floor, Behind Famous Studio, Opp. E Moses Road, Mahalaxmi (West)\nMumbai,\nMaharashtra,\nIndia,\n400011.\n', 'Dhruval Bhuva: This address right\n', 'Dhruval Bhuva: Yes paid\n', 'Dhruval Bhuva: Yes we have to enroll for one additional course\n', 'FHWS Aniket 🇩🇪: +1\n', "FHWS Aniket 🇩🇪: Let's meet\n", 'FHWS Aniket 🇩🇪: Time?\n', "FHWS Aniket 🇩🇪: It's 12:30 for me\n", 'Dhruval Bhuva: Same\n', "Dhruval Bhuva: But I'll take primium\n", 'FHWS Aniket 🇩🇪: 🥳\n', "Dhruval Bhuva: So I'll go at 8\n", 'FHWS Aniket 🇩🇪: Oh\n', 'Dhruval Bhuva: Will you take\n', 'Dhruval Bhuva: Or normal\n', 'FHWS Aniket 🇩🇪: How much time did they take to reflect?\n', 'FHWS Aniket 🇩🇪: All in English?\n', 'Dhruval Bhuva: Means\n', 'FHWS Aniket 🇩🇪: I am also taking premium\n', "Dhruval Bhuva: Cool then let's meet at 8 to 8.30\n", 'FHWS Aniket 🇩🇪: After paying fees, portal mein kab reflect hoga?\n', "FHWS Aniket 🇩🇪: I'll be little late.. i am traveling from Pune same day early in morning. Ill reach by 10-10:30\n", 'Dhruval Bhuva: I paid on 23\nI paid 146 euro + additional charges.\n\nThought they are saying they have received only 123 euro 🥲\n', 'FHWS Aniket 🇩🇪: Why so!\n', "Dhruval Bhuva: Don't know\nMy bank is saying they have paid 146 and also gave me proof\n", 'Dhruval Bhuva: But University is saying they have received only 123\n', 'Dhruval Bhuva: So need to pay 23 euro additional\n', 'Dhruval Bhuva: Did you accept\n', 'Dhruval Bhuva: Let me save your number\nAnkit right\n', "FHWS Aniket 🇩🇪: It's Aniket\n", 'FHWS Aniket 🇩🇪: Oh, probably transaction fees\n', 'FHWS Aniket 🇩🇪: Not yet\n', "Dhruval Bhuva: Hey bro\nWhat's your visa status\n", 'FHWS Aniket 🇩🇪: <Media omitted>\n', 'FHWS Aniket 🇩🇪: this is the last mail I received\n', 'FHWS Aniket 🇩🇪: wbu?\n', 'Dhruval Bhuva: I had mailed them regarding my status\nThey replied after 9 days\n', 'Dhruval Bhuva: <Media omitted>\n', 'Dhruval Bhuva: Still it is not reached physically\n', 'FHWS Aniket 🇩🇪: bhai physical mein itna time kyun?\n', 'FHWS Aniket 🇩🇪: kya mail dala tha?\n', "FHWS Aniket 🇩🇪: I'll also send today and check the status\n", "Dhruval Bhuva: Don't know bro\nBut i think they are verifying documents..\n\nYesterday I company project manager was saying is got call for verification\n", "Dhruval Bhuva: They didn't enclosed their identity\nBut i gussa they might be for visa process\n", 'FHWS Aniket 🇩🇪: Omg!\n', 'FHWS Aniket 🇩🇪: I have no idea about this\n', 'FHWS Aniket 🇩🇪: accommodation?\n', "Dhruval Bhuva: Even I\nMy company guy was saying\nThat's why I get to know\n", 'FHWS Aniket 🇩🇪: oh, got it\n', 'Dhruval Bhuva: Yes I have found one\nBut that guy is also not replying properly 😅\n', 'FHWS Aniket 🇩🇪: private?\n', 'Dhruval Bhuva: Yes\n', 'FHWS Aniket 🇩🇪: wg gesucht?\n', "Dhruval Bhuva: He gives reply every 2 days\nWhy such don't know\n", 'Dhruval Bhuva: Yeah\n', 'FHWS Aniket 🇩🇪: I did not get confirmation about fees from uni\n', "Dhruval Bhuva: No they'll don't send\n", "Dhruval Bhuva: On your portal it'll be change\n", 'Dhruval Bhuva: My status change after yesterday only\n', 'FHWS Aniket 🇩🇪: I paid on 8th feb\n', 'FHWS Aniket 🇩🇪: It did not change\n', 'Dhruval Bhuva: Bro I had paid on 23 Jan\n', 'FHWS Aniket 🇩🇪: did you get any mail for change in status?\n', 'FHWS Aniket 🇩🇪: oh, long back\n', 'Dhruval Bhuva: Noo\n', 'FHWS Aniket 🇩🇪: then I guess they will take more time for me\n', 'Dhruval Bhuva: Yeah it takes around 25 days\n', 'FHWS Aniket 🇩🇪: okok\n', 'FHWS Aniket 🇩🇪: flights?\n', 'FHWS Aniket 🇩🇪: I booked on 15th March, Gulf Air\n', "Dhruval Bhuva: You'll get 'enrolled' as status\n", 'FHWS Aniket 🇩🇪: Mumbai-Bahrain-Frankfurt\n', 'Dhruval Bhuva: Same on 13th\n', 'Dhruval Bhuva: Same\n', 'FHWS Aniket 🇩🇪: 38k?\n', 'Dhruval Bhuva: Yeah 😂\n', 'FHWS Aniket 🇩🇪: great dude!\n', 'FHWS Aniket 🇩🇪: Excited to meet you\n', "Dhruval Bhuva: But as per today's status of visa\nI don't think I'll get visa on around 10\n", 'FHWS Aniket 🇩🇪: I think you will get it\n', 'Dhruval Bhuva: Hope get\nOtherwise will have to pay for flight date change\n', 'Dhruval Bhuva: Hope\n', 'FHWS Aniket 🇩🇪: 28 days generally\n', 'Dhruval Bhuva: Same bro 🥂\n', 'FHWS Aniket 🇩🇪: in that case lets fly together😉\n', "Dhruval Bhuva: Yeah Then I'll change 15\n", 'FHWS Aniket 🇩🇪: yes\n', 'FHWS Aniket 🇩🇪: Let me know once you get any update\n', 'Dhruval Bhuva: Sure\n', 'FHWS Aniket 🇩🇪: Atleast we know each other virtually now\n', 'FHWS Aniket 🇩🇪: do you have any friends there?\n', 'Dhruval Bhuva: Yeah\n', 'FHWS Aniket 🇩🇪: good to know!\n', 'Dhruval Bhuva: But he is also vertically 😂\n', 'Dhruval Bhuva: He is from my town\n', "FHWS Aniket 🇩🇪: I don't have any friends in Germany!\n", 'FHWS Aniket 🇩🇪: sab US chale gaye\n', 'FHWS Aniket 🇩🇪: 😂😂\n', 'Dhruval Bhuva: Bhai 50lakh aram se 🥲\n', 'FHWS Aniket 🇩🇪: paisa bhai\n', 'FHWS Aniket 🇩🇪: aur kuch nahi\n', 'Dhruval Bhuva: Haa vo to bol raha hu\n', 'Dhruval Bhuva: 4 5 loan leni padegi\n', 'Dhruval Bhuva: 😂😂\n', "Dhruval Bhuva: I'm talking about mine\nNot yours 😛\n", 'FHWS Aniket 🇩🇪: are same hain mera case\n', 'FHWS Aniket 🇩🇪: whats your B.tech in btw?\n', 'FHWS Aniket 🇩🇪: CS?\n', 'Dhruval Bhuva: CE\n', 'FHWS Aniket 🇩🇪: I did my B.Tech In ECE from MIT in 2022\n', "Dhruval Bhuva: Bro is it fine if we don't go clg on 1st day\n", "Dhruval Bhuva: Bcz I haven't made payment yet\n", "Dhruval Bhuva: So I'm booking 15th\n", 'FHWS Aniket 🇩🇪: yes, its fine\n', 'FHWS Aniket 🇩🇪: Actually, its my Bday on 15th\n', 'FHWS Aniket 🇩🇪: So I wanted to celebrate it with my family\n', 'Dhruval Bhuva: Yeah\n', 'Dhruval Bhuva: Obviously\n', 'FHWS Aniket 🇩🇪: The university has given extension until 22nd\n', 'FHWS Aniket 🇩🇪: so that okay if we go 1 day late\n', 'Dhruval Bhuva: Cool\n', 'Dhruval Bhuva: Booking on 15th\n', 'FHWS Aniket 🇩🇪: cool\n', 'FHWS Aniket 🇩🇪: lets go together😂\n', 'Dhruval Bhuva: Bro did you choose window seat\n', 'Dhruval Bhuva: May I know your seat raw\n', 'FHWS Aniket 🇩🇪: yes\n', "Dhruval Bhuva: What's yours\n", 'Dhruval Bhuva: I wanted to know bcz what if I choose window seat and get on wings\n', 'Dhruval Bhuva: So I only have to see wings 😂\n', 'FHWS Aniket 🇩🇪: <Media omitted>\n', 'FHWS Aniket 🇩🇪: *share\n', 'FHWS Aniket 🇩🇪: Economoy standard\n', 'FHWS Aniket 🇩🇪: *Economy\n', 'Dhruval Bhuva: <Media omitted>\n', 'Dhruval Bhuva: Wing is not there right\n', 'FHWS Aniket 🇩🇪: yeahhhhh😂\n', 'FHWS Aniket 🇩🇪: yaar I just opted for better legspace\n', 'FHWS Aniket 🇩🇪: I checked the flight details on google\n', 'Dhruval Bhuva: Cool I book same raw opposite part\n', 'FHWS Aniket 🇩🇪: from that I am hoping wings are not near\n', "Dhruval Bhuva: Yeah that's why asking\n", 'FHWS Aniket 🇩🇪: chalega\n', "Dhruval Bhuva: Bro I'm not able to pay\n", 'Dhruval Bhuva: Do they accept axis card\n', 'Dhruval Bhuva: <Media omitted>\n', 'FHWS Aniket 🇩🇪: Yess, all cards are accepted\n', 'FHWS Aniket 🇩🇪: Try again with other card\n', 'Dhruval Bhuva: Yeah\n', 'Dhruval Bhuva: <Media omitted>\n', 'Dhruval Bhuva: Means as it is\n', 'Dhruval Bhuva: Sry for such magges 😂😂\n', 'FHWS Aniket 🇩🇪: yes bro\n', 'FHWS Aniket 🇩🇪: I also kept 0\n', 'FHWS Aniket 🇩🇪: standard economy mein 23*2 + cabin allowed hain\n', 'FHWS Aniket 🇩🇪: + students baggage mein extra 23 likha hain on gulf air website\n', 'Dhruval Bhuva: No \nI called and they said\n', 'FHWS Aniket 🇩🇪: to total 23*3 + Cabin\n', 'Dhruval Bhuva: Let me first finish this\n', 'FHWS Aniket 🇩🇪: okok\n', 'FHWS Aniket 🇩🇪: <Media omitted>\n', 'FHWS Aniket 🇩🇪: https://www.gulfair.com/your-journey/baggage\n', 'Dhruval Bhuva: F\nAgain error\n', 'Dhruval Bhuva: When I enter card otp\nThey show error popup and redirect me on home page\n', 'Dhruval Bhuva: 2 times\n', 'Dhruval Bhuva: We are allowed\n2*32 kg\n6 kg cabin bag\n1 laptop bag\n', 'Dhruval Bhuva: On valid student visa\n', 'FHWS Aniket 🇩🇪: oh!\n', 'FHWS Aniket 🇩🇪: might be server error\n', 'FHWS Aniket 🇩🇪: try later\n', 'Dhruval Bhuva: Yeah will try after a hour\n', "Dhruval Bhuva: Hope price don't get changed\n", "FHWS Aniket 🇩🇪: don't worry\n", 'FHWS Aniket 🇩🇪: abhi kitna dikha?\n', 'FHWS Aniket 🇩🇪: the flight is almost empty\n', 'Dhruval Bhuva: Same as yours\n', 'Dhruval Bhuva: Thought 13th price goes 48k\n', 'Dhruval Bhuva: 37 to 48\n', 'FHWS Aniket 🇩🇪: f!\n', "Dhruval Bhuva: On my passport first name my father's name is joined and on ticket i forgot to join it\n\nDo you think it will create problem while claiming for student visa\n", "FHWS Aniket 🇩🇪: It won't create any issues\n", 'FHWS Aniket 🇩🇪: Dont worry\n', 'Dhruval Bhuva: <Media omitted>\n', 'FHWS Aniket 🇩🇪: 🍺\n', 'Dhruval Bhuva: Bro nahi chalega\n', 'Dhruval Bhuva: It should match our passport name\n', 'Dhruval Bhuva: And name change charges is 100 USD 🥲😂\n', 'Dhruval Bhuva: Ab bol rahe hai chalega 😂\n', 'Dhruval Bhuva: I called 2 3 times to different help center\n', 'Dhruval Bhuva: Every one gave different ans\n', 'FHWS Aniket 🇩🇪: Are yaar\n', 'FHWS Aniket 🇩🇪: Ye kya scene hain\n', 'FHWS Aniket 🇩🇪: <Media omitted>\n', 'FHWS Aniket 🇩🇪: Bro Mera bhi scene hoga kya fir?\n', 'FHWS Aniket 🇩🇪: .\n', 'Dhruval Bhuva: Haan same problem hai\n', 'Dhruval Bhuva: 😂😂\n', "Dhruval Bhuva: But many people are saying it's okay\n\nOne of friends has vistara flight.. they said it's creat prob and they change name on the spot\n", 'Dhruval Bhuva: Vistra change free of cost\n', 'Dhruval Bhuva: Gulf charges 100 USD\n+ Price difference\n+ Tax\n', 'FHWS Aniket 🇩🇪: Yaar pr naam to sahi hain na\n', 'FHWS Aniket 🇩🇪: First name last name same hain\n', 'FHWS Aniket 🇩🇪: Aur kya chahiye\n', 'FHWS Aniket 🇩🇪: Passport no same hain\n', 'Dhruval Bhuva: Vahi to\n', 'Dhruval Bhuva: Ku6 nahi jane dona\nDekh lenge airport par\n', 'Dhruval Bhuva: 25k thodi name change ke hote hai\n', 'FHWS Aniket 🇩🇪: Na koi spelling mistake, na koi changes\n', 'FHWS Aniket 🇩🇪: Bas middle name nahi lagaya\n', 'Dhruval Bhuva: Haan jane do\n', 'Dhruval Bhuva: Dekha jayega\n', 'FHWS Aniket 🇩🇪: Ha\n', 'Dhruval Bhuva: Air india said no\nName should same 😂\n', 'Dhruval Bhuva: Only gulf people not aware\n', 'FHWS Aniket 🇩🇪: Are bhai\n', 'Dhruval Bhuva: Did you received any single update after 1st text msg\n', 'FHWS Aniket 🇩🇪: Nope 😂\n', 'FHWS Aniket 🇩🇪: Did you?\n', 'Dhruval Bhuva: Noo\n', 'Dhruval Bhuva: Ticket to karali hai bhai\n', 'Dhruval Bhuva: Milto jayega na\n', 'Dhruval Bhuva: <Media omitted>\n', 'FHWS Aniket 🇩🇪: \U0001f979\n', 'FHWS Aniket 🇩🇪: Bhai, ese mat soch\n', 'FHWS Aniket 🇩🇪: Milega milega\n', 'FHWS Aniket 🇩🇪: 1 month to lagta hain\n', 'Dhruval Bhuva: My one frd got dispatched msg within 4 days\n', 'Dhruval Bhuva: 😂😂\n', 'FHWS Aniket 🇩🇪: Mail kr unko\n', 'FHWS Aniket 🇩🇪: I did it yesterday\n', 'Dhruval Bhuva: My reply is pending\n', 'FHWS Aniket 🇩🇪: Even one of my friends got it in 7 days\n', 'FHWS Aniket 🇩🇪: Kab mail Kiya?\n', 'Dhruval Bhuva: Or ek ham 😂😂\n', 'FHWS Aniket 🇩🇪: State wise bhi differ karta hoga shayad\n', 'Dhruval Bhuva: 7 \n13\n18\n', 'FHWS Aniket 🇩🇪: Mein wo enrolment ka bhi nahi aya\n', 'FHWS Aniket 🇩🇪: Wo Moodle ke course ka access nahi hain mere pass\n', 'Dhruval Bhuva: Recived reply of 7th mail\n', 'Dhruval Bhuva: Mail kr bhai\n', 'Dhruval Bhuva: Payment kar diya hai kya\n', 'FHWS Aniket 🇩🇪: Na sem contribution ki receipt\n', 'FHWS Aniket 🇩🇪: 8th feb\n', 'Dhruval Bhuva: Nahi vo nahi ayegi\n', 'Dhruval Bhuva: Mail kr bhai\n', 'FHWS Aniket 🇩🇪: Sahi hain.. meine bas 1 dala .. aur wo kal..\nAbhi tuzhe aga 7th ka kal reply aya.. to mujhe to visa aane ke bad ayega shayad 😂\n', 'Dhruval Bhuva: Usko likh ki enrollment credits provide kro\nPre Course start karna hai\n\nAnd also attended paid fees receipt\n', 'FHWS Aniket 🇩🇪: Karta hu\n', 'FHWS Aniket 🇩🇪: Thik hain\n', 'Dhruval Bhuva: 😂😂😂\n', 'Dhruval Bhuva: <Media omitted>\n', 'FHWS Aniket 🇩🇪: 😂😂\n', 'FHWS Aniket 🇩🇪: Bhai wo name change ka kya scene?\n', 'FHWS Aniket 🇩🇪: Tune pre courses shuru kiye?\n', 'FHWS Aniket 🇩🇪: Aur accomodation?\n', 'Dhruval Bhuva: Haa vo mene 3 4 agent se bat ki\n\nNahi hoga problem in 95% case\n', 'Dhruval Bhuva: Python ka kiya\n\nKu6 nahi hai\nQuite easy\n', 'FHWS Aniket 🇩🇪: 😂\n', 'FHWS Aniket 🇩🇪: Accessssss!!!!\n', 'Dhruval Bhuva: Ek jagah bat chal rahi thi\nMana kar diya usne\n', 'FHWS Aniket 🇩🇪: Login creds ka mail aya tuzhe?\n', 'Dhruval Bhuva: Ab dusra koi reply nhi deta 😂😂\n', 'FHWS Aniket 🇩🇪: Hashhh!\n', 'Dhruval Bhuva: Nono\n\nVo tamare portal par pdf hogi.. like offer letter\n', 'FHWS Aniket 🇩🇪: 😅 mera same case hain\n', 'FHWS Aniket 🇩🇪: Accha\n', 'Dhruval Bhuva: Ek frd ko Mila\n\nBahut a6a landowner hai\n', 'Dhruval Bhuva: Usko frankfurt tak apni car leke lene jana vala jai\n', 'Dhruval Bhuva: 😂😂😂\n', 'Dhruval Bhuva: Or ek ham ... Koi reply tak nhi deta\n', 'FHWS Aniket 🇩🇪: Female hain kya 😂\n', 'Dhruval Bhuva: You catch it 😜\n', 'Dhruval Bhuva: <Media omitted>\n', 'FHWS Aniket 🇩🇪: Lol 😂\nThe entire world is the same\n', 'Dhruval Bhuva: Can you once verify luggage weight with airline\n\nI just called i per I understand we are allowed 32 + 32 + 6 + laptop bag\n', "Dhruval Bhuva: And while Booking tickets I haven't choosen student anywhere, so we have to show on airport only right ?\n", 'FHWS Aniket 🇩🇪: Yes at the airport during check-in\n', 'FHWS Aniket 🇩🇪: Yes, I will confirm once\n', 'Dhruval Bhuva: And what if they denied 😂\n', 'FHWS Aniket 🇩🇪: Udhar hi nikal ke rakhenge 😂\n', 'Dhruval Bhuva: We will have to unpack all bags\n', 'Dhruval Bhuva: Yeah please 😂\n', 'FHWS Aniket 🇩🇪: Ha\n', 'FHWS Aniket 🇩🇪: Bhai accommodation yaar!\n', 'FHWS Aniket 🇩🇪: Abhi tak nahi mila\n', 'Dhruval Bhuva: Same here\n', 'Dhruval Bhuva: Ek refrence hai tume chahiye to\n\n540 rent\n700 deposit\n', 'FHWS Aniket 🇩🇪: Please\n', 'FHWS Aniket 🇩🇪: Contact?\n', 'Dhruval Bhuva: +49 1577 5687456\n', "Dhruval Bhuva: It's in 522 Apartunities\n", 'FHWS Aniket 🇩🇪: Ok\n', 'FHWS Aniket 🇩🇪: Pucha hain\n', "FHWS Aniket 🇩🇪: Let's see\n", 'Dhruval Bhuva: Yeah\n', 'Dhruval Bhuva: But sab information to tume website par mil jayegi\n', 'Dhruval Bhuva: 522 Apartunities würzburg\n\nIs par private room hai\n', 'Dhruval Bhuva: Min stay duration 6 month\n', 'FHWS Aniket 🇩🇪: Ha\n', 'FHWS Aniket 🇩🇪: What are your preferences?\n', "Dhruval Bhuva: It's costly for me 😅\n", 'FHWS Aniket 🇩🇪: +1\n', 'FHWS Aniket 🇩🇪: Obviously\n', 'Dhruval Bhuva: I had 2 3 contact such\n\nTume muje batana chahiye na ki tume chalega 😅\n', 'FHWS Aniket 🇩🇪: 😂 chalega bhai\n', 'FHWS Aniket 🇩🇪: But mein bhi around 250-350 tak hi dekh raha hu\n', "Dhruval Bhuva: 1 2 month initially stay kar skta hu\n\nLekin jo vo condition hai na\n6 month vali\n\nIt's dangerous 😭\n", 'Dhruval Bhuva: 540 is double 😂\n', 'FHWS Aniket 🇩🇪: True!\n', 'FHWS Aniket 🇩🇪: Kuch nahi se atleast kuch hai tak ka safar 😂\n', 'FHWS Aniket 🇩🇪: Backup!\n', 'Dhruval Bhuva: Sahi hai 😂\n', 'FHWS Aniket 🇩🇪: Visa update?\n', 'Dhruval Bhuva: Nope\n', 'Dhruval Bhuva: <Media omitted>\n', 'Dhruval Bhuva: Means ?\n', 'FHWS Aniket 🇩🇪: Congratulations 🎉\n', 'FHWS Aniket 🇩🇪: Ho Gaya visa ka kam\n', 'FHWS Aniket 🇩🇪: Courier ho ke ayega ab ghar 2 din mein\n', 'FHWS Aniket 🇩🇪: You submitted docs on 30th Jan morning right?\n', 'Dhruval Bhuva: Sure 😃\n', 'Dhruval Bhuva: ?\n', 'Dhruval Bhuva: <Media omitted>\n', 'Dhruval Bhuva: Yeah\n', 'Dhruval Bhuva: Did you get any update\n', 'FHWS Aniket 🇩🇪: Damm suree\n', 'Dhruval Bhuva: <Media omitted>\n', 'FHWS Aniket 🇩🇪: Nope\n', "Dhruval Bhuva: We had on same day, isn't\n", 'FHWS Aniket 🇩🇪: Karlo party\n', 'FHWS Aniket 🇩🇪: Yep afternoon\n', 'Dhruval Bhuva: Ohh\n', "Dhruval Bhuva: You'll also get soon\n", 'FHWS Aniket 🇩🇪: Hoping mail aa jayega aaj nahi to kal\n', 'FHWS Aniket 🇩🇪: Bingoo\n', 'Dhruval Bhuva: Haha ahi jayega na 😂\n', "Dhruval Bhuva: Let's packing\n", 'Dhruval Bhuva: <Media omitted>\n', 'FHWS Aniket 🇩🇪: YeH 😂\n', 'FHWS Aniket 🇩🇪: Ab ghar ka dekhteeeee\n', 'Dhruval Bhuva: Or ek mila gai\n', 'Dhruval Bhuva: 413 rent\n', 'FHWS Aniket 🇩🇪: Shared?\n', 'FHWS Aniket 🇩🇪: Sath mein dekhe?\n', 'Dhruval Bhuva: Lekin ab reply nahi kar raha 🥲\n', 'FHWS Aniket 🇩🇪: Ya koi hain tere sath\n', 'Dhruval Bhuva: Yeah\n', 'Dhruval Bhuva: Nahi bro\n', 'FHWS Aniket 🇩🇪: Bhai ye to ab aadat ho gayi hain 😂\n', 'Dhruval Bhuva: Pahele usne visit ke liye invitation diya\n\nMene bola IND me hu\n', 'Dhruval Bhuva: Online kar lete hai\n', 'Dhruval Bhuva: To ab no reply\n', 'FHWS Aniket 🇩🇪: Ok\n', 'FHWS Aniket 🇩🇪: Ye kya hain bc! 😂\n', 'Dhruval Bhuva: I think vo physically face dekh kar hi dete hoge\n', 'FHWS Aniket 🇩🇪: 😶\n', 'Dhruval Bhuva: Esa hai kya ?\n', 'FHWS Aniket 🇩🇪: Ese to aur bhi difficult hain na bhai\n', 'FHWS Aniket 🇩🇪: Fir to udhar jake hi dhundna padega\n', 'Dhruval Bhuva: Esa nhi hota I guess 😅\n', 'Dhruval Bhuva: Many people got from India it self\n', 'Dhruval Bhuva: But the person we are facing, he is only that kind of 🥱🥱\n', 'FHWS Aniket 🇩🇪: Dekhte!\n', "FHWS Aniket 🇩🇪: Let's hope acchi deal mile\n", 'Dhruval Bhuva: Hmm\n', 'FHWS Aniket 🇩🇪: <Media omitted>\n', 'FHWS Aniket 🇩🇪: Ye lo aa gaya mail abhi\n', 'Dhruval Bhuva: Congratulations 🎉👏\n', 'Dhruval Bhuva: Start packing\n', 'FHWS Aniket 🇩🇪: Yes\n', 'FHWS Aniket 🇩🇪: Bags le liye?\n', 'Dhruval Bhuva: Yeah\n', 'Dhruval Bhuva: https://www.amazon.in/VIP-Cosmos-Trolley-Polypropylene-Suitcase/dp/B0BR4DQ1BK/ref=mp_s_a_1_25?qid=1676394920&refinements=p_89%3AVIP&s=luggage&sr=1-25\n', 'FHWS Aniket 🇩🇪: Meine bhi VIP hi liya 😂\n', "Dhruval Bhuva: You'll get dispatched on same day\n", 'Dhruval Bhuva: I think\n', 'Dhruval Bhuva: As you are nearer to Mumbai\n', 'Dhruval Bhuva: Cool\n', 'FHWS Aniket 🇩🇪: Pune\n', 'Dhruval Bhuva: We have flight at 9.34 PM right\n', 'Dhruval Bhuva: At night\n', 'FHWS Aniket 🇩🇪: Yes\n', 'FHWS Aniket 🇩🇪: Bro, I received the VISA just now\n', 'Dhruval Bhuva: Finally 🥳\n', 'Dhruval Bhuva: <Media omitted>\n', 'Dhruval Bhuva: Means around 2 3 AM at night according to Germany time\n', 'FHWS Aniket 🇩🇪: Even I am confused about it\n', 'Dhruval Bhuva: <Media omitted>\n', 'Dhruval Bhuva: <Media omitted>\n', 'Dhruval Bhuva: According to 12.55 hr flyover\n', 'FHWS Aniket 🇩🇪: Need to check once\n', 'Dhruval Bhuva: Do you want to book train from Frankfurt to Wurzbug\n', 'Dhruval Bhuva: On 16th March\n', "Dhruval Bhuva: I'm booking\n", 'FHWS Aniket 🇩🇪: Yess\n', 'FHWS Aniket 🇩🇪: From where?\n', 'Dhruval Bhuva: Frankfurt to Wurzbug\n', 'FHWS Aniket 🇩🇪: I mean\n', 'FHWS Aniket 🇩🇪: App website\n', 'FHWS Aniket 🇩🇪: Bro, accommodation?\n', 'Dhruval Bhuva: Mera ek frd kar raha hai\nUske account se\n', 'Dhruval Bhuva: Ham usko lend krke in case dedenge\n', 'FHWS Aniket 🇩🇪: Accha\n', 'FHWS Aniket 🇩🇪: Works\n', 'Dhruval Bhuva: Nhi mila\n', 'Dhruval Bhuva: To bhai teri bhi karneko bolu na\n', 'Dhruval Bhuva: <Media omitted>\n', 'FHWS Aniket 🇩🇪: Yess\n', 'FHWS Aniket 🇩🇪: 2nd karle?\n', 'Dhruval Bhuva: 1st ho jayega aram se\n', 'Dhruval Bhuva: 6 vaje land karenge\n', 'Dhruval Bhuva: 3.5 HR me aram se free ho jayenge\n', 'FHWS Aniket 🇩🇪: Done\n', 'FHWS Aniket 🇩🇪: Gpay karna hain?\n', 'Dhruval Bhuva: Vo usko puchh lunga\n', 'FHWS Aniket 🇩🇪: Thike\n', 'Dhruval Bhuva: Euro chahiye ya inr\n', 'FHWS Aniket 🇩🇪: Okay\n', 'Dhruval Bhuva: Bhai use nhi hogi identity issue ayega so\n', 'Dhruval Bhuva: Hame khud hi karni padegi\n', 'FHWS Aniket 🇩🇪: Acha koi nai\n', 'FHWS Aniket 🇩🇪: Kal karte\n', 'Dhruval Bhuva: Okay\n', 'FHWS Aniket 🇩🇪: 9:34 vali hi na fir?\n', 'Dhruval Bhuva: Bhai vo sai 11 ya 12 ko jane vala hai\nUsko pu6 lenge \nAirport se bar niklne

In [5]:
dates = re.findall(pattern, data)
print(dates)

['08/01/2023, 10:29 - ', '28/01/2023, 07:48 - ', '28/01/2023, 07:48 - ', '28/01/2023, 07:48 - ', '28/01/2023, 07:49 - ', '28/01/2023, 07:49 - ', '28/01/2023, 08:06 - ', '28/01/2023, 08:06 - ', '28/01/2023, 08:06 - ', '28/01/2023, 08:38 - ', '28/01/2023, 08:38 - ', '28/01/2023, 08:38 - ', '28/01/2023, 08:39 - ', '28/01/2023, 08:39 - ', '28/01/2023, 08:41 - ', '28/01/2023, 08:41 - ', '28/01/2023, 08:41 - ', '28/01/2023, 08:42 - ', '28/01/2023, 08:50 - ', '28/01/2023, 08:50 - ', '28/01/2023, 08:50 - ', '28/01/2023, 08:50 - ', '28/01/2023, 08:50 - ', '28/01/2023, 08:51 - ', '28/01/2023, 08:51 - ', '28/01/2023, 08:51 - ', '28/01/2023, 08:51 - ', '28/01/2023, 08:51 - ', '28/01/2023, 08:51 - ', '28/01/2023, 08:51 - ', '28/01/2023, 08:51 - ', '28/01/2023, 08:52 - ', '28/01/2023, 08:52 - ', '28/01/2023, 08:52 - ', '28/01/2023, 08:52 - ', '28/01/2023, 08:53 - ', '28/01/2023, 08:53 - ', '28/01/2023, 08:53 - ', '28/01/2023, 08:54 - ', '28/01/2023, 08:54 - ', '28/01/2023, 08:54 - ', '28/01/2023, 08:55 - ', '28/01/2023, 08:55 - ', '29/01/2023, 12:21 - ', '29/01/2023, 12:21 - ', '29/01/2023, 12:21 - ', '15/02/2023, 11:02 - ', '15/02/2023, 12:07 - ', '15/02/2023, 12:08 - ', '15/02/2023, 12:08 - ', '15/02/2023, 12:08 - ', '15/02/2023, 12:09 - ', '15/02/2023, 12:09 - ', '15/02/2023, 12:09 - ', '15/02/2023, 12:10 - ', '15/02/2023, 12:10 - ', '15/02/2023, 12:10 - ', '15/02/2023, 12:11 - ', '15/02/2023, 12:11 - ', '15/02/2023, 12:11 - ', '15/02/2023, 12:11 - ', '15/02/2023, 12:11 - ', '15/02/2023, 12:12 - ', '15/02/2023, 12:12 - ', '15/02/2023, 12:12 - ', '15/02/2023, 12:12 - ', '15/02/2023, 12:12 - ', '15/02/2023, 12:12 - ', '15/02/2023, 12:12 - ', '15/02/2023, 12:13 - ', '15/02/2023, 12:14 - ', '15/02/2023, 12:14 - ', '15/02/2023, 12:14 - ', '15/02/2023, 12:15 - ', '15/02/2023, 12:15 - ', '15/02/2023, 12:15 - ', '15/02/2023, 12:15 - ', '15/02/2023, 12:15 - ', '15/02/2023, 12:15 - ', '15/02/2023, 12:15 - ', '15/02/2023, 12:15 - ', '15/02/2023, 12:16 - ', '15/02/2023, 12:16 - ', '15/02/2023, 12:16 - ', '15/02/2023, 12:16 - ', '15/02/2023, 12:16 - ', '15/02/2023, 12:16 - ', '15/02/2023, 12:16 - ', '15/02/2023, 12:16 - ', '15/02/2023, 12:16 - ', '15/02/2023, 12:16 - ', '15/02/2023, 12:16 - ', '15/02/2023, 12:17 - ', '15/02/2023, 12:17 - ', '15/02/2023, 12:17 - ', '15/02/2023, 12:17 - ', '15/02/2023, 12:17 - ', '15/02/2023, 12:17 - ', '15/02/2023, 12:18 - ', '15/02/2023, 12:18 - ', '15/02/2023, 12:18 - ', '15/02/2023, 12:18 - ', '15/02/2023, 12:18 - ', '15/02/2023, 12:18 - ', '15/02/2023, 12:19 - ', '15/02/2023, 12:19 - ', '15/02/2023, 12:19 - ', '15/02/2023, 12:19 - ', '15/02/2023, 12:20 - ', '15/02/2023, 12:20 - ', '15/02/2023, 12:20 - ', '15/02/2023, 12:20 - ', '15/02/2023, 12:20 - ', '15/02/2023, 12:20 - ', '15/02/2023, 12:20 - ', '15/02/2023, 12:21 - ', '15/02/2023, 12:21 - ', '15/02/2023, 12:21 - ', '15/02/2023, 12:21 - ', '15/02/2023, 12:21 - ', '15/02/2023, 12:22 - ', '15/02/2023, 12:22 - ', '15/02/2023, 12:22 - ', '15/02/2023, 12:22 - ', '15/02/2023, 12:55 - ', '15/02/2023, 12:55 - ', '15/02/2023, 12:55 - ', '15/02/2023, 12:58 - ', '15/02/2023, 12:59 - ', '15/02/2023, 12:59 - ', '15/02/2023, 12:59 - ', '15/02/2023, 12:59 - ', '15/02/2023, 12:59 - ', '15/02/2023, 13:00 - ', '15/02/2023, 13:00 - ', '15/02/2023, 13:00 - ', '15/02/2023, 13:00 - ', '15/02/2023, 13:00 - ', '15/02/2023, 13:02 - ', '15/02/2023, 13:02 - ', '15/02/2023, 13:03 - ', '15/02/2023, 13:03 - ', '15/02/2023, 13:04 - ', '15/02/2023, 13:04 - ', '15/02/2023, 13:05 - ', '15/02/2023, 13:05 - ', '15/02/2023, 13:05 - ', '15/02/2023, 13:05 - ', '15/02/2023, 13:06 - ', '15/02/2023, 13:06 - ', '15/02/2023, 13:06 - ', '15/02/2023, 13:07 - ', '15/02/2023, 13:07 - ', '15/02/2023, 13:07 - ', '15/02/2023, 13:08 - ', '15/02/2023, 13:08 - ', '15/02/2023, 13:08 - ', '15/02/2023, 13:17 - ', '15/02/2023, 13:17 - ', '15/02/2023, 13:18 - ', '15/02/2023, 13:28 - ', '15/02/2023, 13:29 - ', '15/02/2023, 13:31 - ', '15/02/2023, 13:45 - ', '15/02/2023, 13:45 - ', '15/02/2023, 13:46 - ', '15/02/2023, 13:48 - ', '15/02/2023, 13:48 - ', '15/02/2023, 13:48 - ', '15/02/2023, 13:49 - ', '15/02/2023, 13:49 - ', '15/02/2023, 13:49 - ', '15/02/2023, 13:49 - ', '15/02/2023, 13:49 - ', '15/02/2023, 13:51 - ', '15/02/2023, 13:51 - ', '15/02/2023, 13:54 - ', '15/02/2023, 13:54 - ', '15/02/2023, 13:54 - ', '15/02/2023, 13:55 - ', '15/02/2023, 13:55 - ', '15/02/2023, 13:56 - ', '15/02/2023, 13:57 - ', '15/02/2023, 13:57 - ', '15/02/2023, 13:57 - ', '15/02/2023, 13:57 - ', '15/02/2023, 13:58 - ', '15/02/2023, 13:58 - ', '15/02/2023, 13:58 - ', '15/02/2023, 13:58 - ', '15/02/2023, 13:59 - ', '15/02/2023, 13:59 - ', '15/02/2023, 14:00 - ', '16/02/2023, 16:57 - ', '16/02/2023, 18:14 - ', '16/02/2023, 18:14 - ', '16/02/2023, 18:21 - ', '16/02/2023, 18:27 - ', '17/02/2023, 10:14 - ', '17/02/2023, 10:14 - ', '17/02/2023, 10:14 - ', '17/02/2023, 11:01 - ', '17/02/2023, 11:01 - ', '17/02/2023, 11:01 - ', '17/02/2023, 12:12 - ', '17/02/2023, 12:13 - ', '17/02/2023, 12:14 - ', '17/02/2023, 12:15 - ', '17/02/2023, 12:15 - ', '17/02/2023, 12:15 - ', '17/02/2023, 12:15 - ', '17/02/2023, 12:16 - ', '17/02/2023, 12:16 - ', '17/02/2023, 12:17 - ', '17/02/2023, 12:18 - ', '17/02/2023, 12:19 - ', '17/02/2023, 12:19 - ', '17/02/2023, 12:19 - ', '17/02/2023, 12:19 - ', '17/02/2023, 12:19 - ', '17/02/2023, 12:19 - ', '17/02/2023, 12:19 - ', '17/02/2023, 12:20 - ', '17/02/2023, 12:23 - ', '17/02/2023, 12:23 - ', '17/02/2023, 12:23 - ', '17/02/2023, 12:23 - ', '17/02/2023, 12:23 - ', '17/02/2023, 12:23 - ', '24/02/2023, 13:58 - ', '24/02/2023, 13:59 - ', '24/02/2023, 13:59 - ', '24/02/2023, 13:59 - ', '24/02/2023, 13:59 - ', '24/02/2023, 13:59 - ', '24/02/2023, 14:00 - ', '24/02/2023, 14:05 - ', '24/02/2023, 14:05 - ', '24/02/2023, 14:05 - ', '24/02/2023, 14:05 - ', '24/02/2023, 14:05 - ', '24/02/2023, 14:06 - ', '24/02/2023, 14:06 - ', '24/02/2023, 14:06 - ', '24/02/2023, 14:06 - ', '24/02/2023, 14:06 - ', '24/02/2023, 14:06 - ', '24/02/2023, 14:06 - ', '24/02/2023, 14:07 - ', '24/02/2023, 14:07 - ', '24/02/2023, 14:07 - ', '24/02/2023, 14:07 - ', '24/02/2023, 14:07 - ', '24/02/2023, 14:07 - ', '24/02/2023, 14:07 - ', '24/02/2023, 14:07 - ', '24/02/2023, 14:08 - ', '24/02/2023, 14:08 - ', '24/02/2023, 14:08 - ', '24/02/2023, 14:08 - ', '24/02/2023, 14:08 - ', '24/02/2023, 14:08 - ', '24/02/2023, 14:09 - ', '24/02/2023, 14:09 - ', '24/02/2023, 14:09 - ', '24/02/2023, 14:09 - ', '24/02/2023, 14:10 - ', '24/02/2023, 14:10 - ', '24/02/2023, 14:10 - ', '24/02/2023, 14:10 - ', '24/02/2023, 14:11 - ', '24/02/2023, 14:11 - ', '24/02/2023, 14:11 - ', '24/02/2023, 14:11 - ', '24/02/2023, 14:11 - ', '24/02/2023, 14:11 - ', '24/02/2023, 14:12 - ', '24/02/2023, 14:12 - ', '24/02/2023, 14:12 - ', '24/02/2023, 14:12 - ', '24/02/2023, 14:13 - ', '24/02/2023, 14:13 - ', '24/02/2023, 14:13 - ', '24/02/2023, 14:13 - ', '25/02/2023, 05:38 - ', '25/02/2023, 05:40 - ', '25/02/2023, 05:40 - ', '25/02/2023, 06:36 - ', '28/02/2023, 07:53 - ', '28/02/2023, 07:54 - ', '28/02/2023, 08:04 - ', '28/02/2023, 08:04 - ', '28/02/2023, 08:04 - ', '28/02/2023, 08:04 - ', '28/02/2023, 08:04 - ', '28/02/2023, 08:05 - ', '28/02/2023, 08:07 - ', '28/02/2023, 08:07 - ', '28/02/2023, 08:08 - ', '28/02/2023, 08:20 - ', '28/02/2023, 08:20 - ', '28/02/2023, 08:30 - ', '28/02/2023, 08:30 - ', '28/02/2023, 08:31 - ', '28/02/2023, 08:31 - ', '28/02/2023, 08:40 - ', '28/02/2023, 08:41 - ', '28/02/2023, 08:41 - ', '28/02/2023, 08:42 - ', '28/02/2023, 08:42 - ', '28/02/2023, 08:43 - ', '28/02/2023, 08:43 - ', '28/02/2023, 08:43 - ', '28/02/2023, 08:43 - ', '28/02/2023, 08:44 - ', '28/02/2023, 08:44 - ', '28/02/2023, 08:44 - ', '28/02/2023, 08:45 - ', '28/02/2023, 08:45 - ', '28/02/2023, 08:46 - ', '28/02/2023, 08:46 - ', '28/02/2023, 08:46 - ', '28/02/2023, 08:46 - ', '28/02/2023, 08:47 - ', '28/02/2023, 08:47 - ', '28/02/2023, 08:47 - ', '28/02/2023, 09:05 - ', '28/02/2023, 09:10 - ', '28/02/2023, 11:22 - ', '28/02/2023, 11:23 - ', '28/02/2023, 12:06 - ', '28/02/2023, 12:06 - ', '28/02/2023, 12:06 - ', '28/02/2023, 12:06 - ', '28/02/2023, 12:06 - ', '28/02/2023, 12:07 - ', '28/02/2023, 12:07 - ', '28/02/2023, 12:07 - ', '28/02/2023, 12:07 - ', '28/02/2023, 12:07 - ', '28/02/2023, 12:07 - ', '28/02/2023, 12:07 - ', '28/02/2023, 12:07 - ', '28/02/2023, 12:07 - ', '28/02/2023, 12:07 - ', '28/02/2023, 12:08 - ', '28/02/2023, 12:08 - ', '28/02/2023, 12:08 - ', '28/02/2023, 12:08 - ', '28/02/2023, 12:08 - ', '28/02/2023, 12:08 - ', '28/02/2023, 12:08 - ', '28/02/2023, 12:08 - ', '28/02/2023, 12:08 - ', '28/02/2023, 12:08 - ', '28/02/2023, 12:08 - ', '28/02/2023, 12:08 - ', '28/02/2023, 12:09 - ', '28/02/2023, 12:09 - ', '28/02/2023, 12:09 - ', '28/02/2023, 12:09 - ', '28/02/2023, 12:09 - ', '28/02/2023, 12:09 - ', '28/02/2023, 12:09 - ', '28/02/2023, 12:09 - ', '28/02/2023, 12:09 - ', '28/02/2023, 12:10 - ', '28/02/2023, 12:10 - ', '28/02/2023, 12:11 - ', '28/02/2023, 12:11 - ', '28/02/2023, 12:11 - ', '28/02/2023, 12:14 - ', '28/02/2023, 12:14 - ', '28/02/2023, 12:15 - ', '28/02/2023, 12:15 - ', '28/02/2023, 12:16 - ', '28/02/2023, 12:16 - ', '28/02/2023, 12:17 - ', '28/02/2023, 12:17 - ', '28/02/2023, 12:19 - ', '28/02/2023, 12:19 - ', '28/02/2023, 12:19 - ', '28/02/2023, 12:19 - ', '28/02/2023, 12:29 - ', '28/02/2023, 12:29 - ', '28/02/2023, 12:29 - ', '28/02/2023, 12:29 - ', '28/02/2023, 12:30 - ', '28/02/2023, 12:38 - ', '28/02/2023, 12:38 - ', '28/02/2023, 12:38 - ', '28/02/2023, 12:39 - ', '28/02/2023, 12:45 - ', '01/03/2023, 08:50 - ', '01/03/2023, 08:50 - ', '01/03/2023, 09:01 - ', '01/03/2023, 09:02 - ', '01/03/2023, 09:03 - ', '01/03/2023, 09:03 - ', '01/03/2023, 09:03 - ', '01/03/2023, 09:04 - ', '01/03/2023, 09:07 - ', '01/03/2023, 09:14 - ', '01/03/2023, 09:14 - ', '01/03/2023, 09:28 - ', '07/03/2023, 17:50 - ', '07/03/2023, 17:50 - ', '07/03/2023, 17:50 - ', '08/03/2023, 03:31 - ', '08/03/2023, 03:31 - ', '08/03/2023, 04:18 - ', '08/03/2023, 04:38 - ', '08/03/2023, 04:38 - ', '08/03/2023, 04:38 - ', '08/03/2023, 05:07 - ', '08/03/2023, 05:07 - ', '08/03/2023, 05:07 - ', '08/03/2023, 05:07 - ', '08/03/2023, 05:07 - ', '08/03/2023, 05:58 - ', '08/03/2023, 05:58 - ', '08/03/2023, 06:40 - ', '08/03/2023, 06:40 - ', '08/03/2023, 06:41 - ', '08/03/2023, 06:41 - ', '08/03/2023, 06:41 - ', '08/03/2023, 06:45 - ', '08/03/2023, 06:45 - ', '08/03/2023, 06:45 - ', '08/03/2023, 06:45 - ', '08/03/2023, 06:46 - ', '08/03/2023, 06:46 - ', '08/03/2023, 18:26 - ', '08/03/2023, 18:27 - ', '08/03/2023, 19:34 - ', '08/03/2023, 19:34 - ', '09/03/2023, 04:29 - ', '09/03/2023, 06:37 - ', '09/03/2023, 06:38 - ', '09/03/2023, 06:39 - ', '09/03/2023, 06:39 - ', '09/03/2023, 06:39 - ', '09/03/2023, 06:39 - ', '09/03/2023, 06:40 - ', '09/03/2023, 07:44 - ', '09/03/2023, 07:44 - ', '09/03/2023, 07:44 - ', '09/03/2023, 07:44 - ', '09/03/2023, 07:45 - ', '09/03/2023, 07:48 - ', '09/03/2023, 07:48 - ', '09/03/2023, 07:48 - ', '09/03/2023, 10:27 - ', '09/03/2023, 10:55 - ', '10/03/2023, 03:41 - ', '10/03/2023, 03:41 - ', '10/03/2023, 03:41 - ', '10/03/2023, 03:45 - ', '10/03/2023, 03:45 - ', '10/03/2023, 03:45 - ', '10/03/2023, 03:45 - ', '10/03/2023, 03:47 - ', '10/03/2023, 03:48 - ', '10/03/2023, 03:48 - ', '10/03/2023, 03:48 - ', '10/03/2023, 03:50 - ', '10/03/2023, 03:50 - ', '10/03/2023, 03:51 - ', '10/03/2023, 04:02 - ', '10/03/2023, 04:02 - ', '10/03/2023, 04:28 - ', '10/03/2023, 04:29 - ', '10/03/2023, 06:28 - ', '10/03/2023, 06:29 - ', '10/03/2023, 08:13 - ', '10/03/2023, 08:16 - ', '10/03/2023, 08:17 - ', '10/03/2023, 08:17 - ', '10/03/2023, 08:17 - ', '11/03/2023, 03:21 - ', '11/03/2023, 03:21 - ', '11/03/2023, 03:21 - ', '11/03/2023, 03:21 - ', '11/03/2023, 03:24 - ', '11/03/2023, 03:26 - ', '11/03/2023, 03:26 - ', '11/03/2023, 03:27 - ', '11/03/2023, 03:27 - ', '11/03/2023, 03:27 - ', '11/03/2023, 03:27 - ', '11/03/2023, 03:28 - ', '11/03/2023, 03:29 - ', '11/03/2023, 03:30 - ', '11/03/2023, 03:30 - ', '11/03/2023, 03:30 - ', '11/03/2023, 03:31 - ', '11/03/2023, 03:31 - ', '11/03/2023, 03:31 - ', '11/03/2023, 03:32 - ', '11/03/2023, 03:32 - ', '11/03/2023, 03:33 - ', '11/03/2023, 03:34 - ', '11/03/2023, 03:34 - ', '11/03/2023, 03:35 - ', '11/03/2023, 03:35 - ', '11/03/2023, 03:35 - ', '11/03/2023, 03:36 - ', '11/03/2023, 03:36 - ', '11/03/2023, 03:37 - ', '11/03/2023, 03:38 - ', '11/03/2023, 03:38 - ', '11/03/2023, 03:38 - ', '11/03/2023, 03:39 - ', '11/03/2023, 03:39 - ', '11/03/2023, 03:40 - ', '11/03/2023, 03:41 - ', '11/03/2023, 03:41 - ', '11/03/2023, 03:42 - ', '11/03/2023, 03:42 - ', '11/03/2023, 03:44 - ', '11/03/2023, 03:45 - ', '11/03/2023, 03:45 - ', '11/03/2023, 03:48 - ', '11/03/2023, 03:50 - ', '11/03/2023, 03:50 - ', '11/03/2023, 03:51 - ', '11/03/2023, 03:51 - ', '11/03/2023, 03:52 - ', '11/03/2023, 03:53 - ', '11/03/2023, 03:57 - ', '11/03/2023, 07:28 - ', '11/03/2023, 07:29 - ', '11/03/2023, 12:11 - ', '11/03/2023, 12:11 - ', '12/03/2023, 08:11 - ', '12/03/2023, 11:00 - ', '12/03/2023, 19:31 - ', '12/03/2023, 19:31 - ', '13/03/2023, 20:47 - ', '13/03/2023, 20:47 - ', '14/03/2023, 03:10 - ', '14/03/2023, 09:13 - ', '14/03/2023, 09:13 - ', '14/03/2023, 09:13 - ', '14/03/2023, 09:32 - ', '14/03/2023, 09:39 - ', '14/03/2023, 10:15 - ', '14/03/2023, 10:15 - ', '14/03/2023, 11:07 - ', '14/03/2023, 11:07 - ', '14/03/2023, 11:07 - ', '14/03/2023, 11:07 - ', '14/03/2023, 11:08 - ', '14/03/2023, 11:08 - ', '14/03/2023, 11:09 - ', '14/03/2023, 11:09 - ', '14/03/2023, 11:13 - ', '14/03/2023, 11:13 - ', '14/03/2023, 11:14 - ', '14/03/2023, 11:14 - ', '14/03/2023, 11:14 - ', '14/03/2023, 11:14 - ', '14/03/2023, 11:14 - ', '14/03/2023, 11:15 - ', '14/03/2023, 11:15 - ', '14/03/2023, 11:15 - ', '14/03/2023, 11:15 - ', '14/03/2023, 11:15 - ', '14/03/2023, 11:15 - ', '14/03/2023, 11:15 - ', '14/03/2023, 11:15 - ', '14/03/2023, 11:15 - ', '14/03/2023, 11:15 - ', '14/03/2023, 11:15 - ', '14/03/2023, 11:15 - ', '14/03/2023, 11:15 - ', '14/03/2023, 11:16 - ', '14/03/2023, 11:16 - ', '14/03/2023, 11:16 - ', '14/03/2023, 11:16 - ', '14/03/2023, 11:16 - ', '14/03/2023, 11:16 - ', '14/03/2023, 11:16 - ', '14/03/2023, 11:16 - ', '14/03/2023, 11:16 - ', '14/03/2023, 11:16 - ', '14/03/2023, 11:16 - ', '14/03/2023, 11:16 - ', '14/03/2023, 11:17 - ', '14/03/2023, 11:17 - ', '14/03/2023, 11:17 - ', '14/03/2023, 11:17 - ', '14/03/2023, 11:17 - ', '14/03/2023, 11:17 - ', '14/03/2023, 11:18 - ', '14/03/2023, 11:18 - ', '14/03/2023, 11:18 - ', '14/03/2023, 11:19 - ', '14/03/2023, 11:20 - ', '15/03/2023, 14:14 - ', '15/03/2023, 14:47 - ', '15/03/2023, 14:48 - ', '15/03/2023, 14:48 - ', '15/03/2023, 14:48 - ', '15/03/2023, 14:54 - ', '15/03/2023, 14:54 - ', '15/03/2023, 14:55 - ', '15/03/2023, 14:55 - ', '15/03/2023, 15:00 - ', '15/03/2023, 15:01 - ', '15/03/2023, 15:02 - ', '15/03/2023, 15:02 - ', '15/03/2023, 15:50 - ', '15/03/2023, 15:56 - ', '15/03/2023, 15:56 - ', '15/03/2023, 15:56 - ', '15/03/2023, 16:00 - ', '15/03/2023, 16:01 - ', '15/03/2023, 16:01 - ', '15/03/2023, 16:01 - ', '15/03/2023, 16:01 - ', '15/03/2023, 16:03 - ', '15/03/2023, 16:04 - ', '15/03/2023, 16:04 - ', '15/03/2023, 16:04 - ', '15/03/2023, 16:05 - ', '15/03/2023, 16:05 - ', '15/03/2023, 16:05 - ', '15/03/2023, 16:05 - ', '15/03/2023, 16:05 - ', '15/03/2023, 16:08 - ', '15/03/2023, 16:11 - ', '15/03/2023, 16:12 - ', '15/03/2023, 16:33 - ', '15/03/2023, 16:33 - ', '15/03/2023, 16:33 - ', '15/03/2023, 16:33 - ', '15/03/2023, 16:35 - ', '15/03/2023, 16:36 - ', '15/03/2023, 16:36 - ', '15/03/2023, 16:36 - ', '15/03/2023, 16:36 - ', '15/03/2023, 16:41 - ', '15/03/2023, 16:41 - ', '15/03/2023, 16:41 - ', '15/03/2023, 16:58 - ', '15/03/2023, 16:58 - ', '15/03/2023, 16:58 - ', '15/03/2023, 16:58 - ', '15/03/2023, 22:38 - ', '15/03/2023, 22:39 - ', '15/03/2023, 22:39 - ', '15/03/2023, 22:39 - ', '15/03/2023, 22:40 - ', '15/03/2023, 23:57 - ', '16/03/2023, 07:44 - ', '16/03/2023, 09:03 - ', '16/03/2023, 09:03 - ', '16/03/2023, 09:03 - ', '16/03/2023, 09:03 - ', '16/03/2023, 09:03 - ', '16/03/2023, 09:03 - ', '16/03/2023, 09:03 - ', '16/03/2023, 09:03 - ', '16/03/2023, 10:25 - ', '16/03/2023, 10:26 - ', '16/03/2023, 10:28 - ', '16/03/2023, 11:54 - ', '16/03/2023, 11:54 - ', '16/03/2023, 11:55 - ', '16/03/2023, 11:56 - ', '16/03/2023, 15:35 - ', '16/03/2023, 15:37 - ', '16/03/2023, 15:45 - ', '16/03/2023, 15:45 - ', '16/03/2023, 15:45 - ', '16/03/2023, 15:46 - ', '16/03/2023, 16:33 - ', '16/03/2023, 17:06 - ', '16/03/2023, 20:34 - ', '16/03/2023, 20:41 - ', '17/03/2023, 06:32 - ', '17/03/2023, 07:23 - ', '17/03/2023, 07:32 - ', '17/03/2023, 07:33 - ', '17/03/2023, 07:40 - ', '17/03/2023, 07:50 - ', '17/03/2023, 07:50 - ', '17/03/2023, 10:24 - ', '17/03/2023, 14:23 - ', '17/03/2023, 14:25 - ', '17/03/2023, 14:49 - ', '18/03/2023, 08:35 - ', '18/03/2023, 09:33 - ', '18/03/2023, 09:33 - ', '18/03/2023, 10:15 - ', '18/03/2023, 10:15 - ', '18/03/2023, 10:36 - ', '18/03/2023, 12:19 - ', '18/03/2023, 13:24 - ', '18/03/2023, 13:24 - ', '18/03/2023, 13:24 - ', '18/03/2023, 14:02 - ', '18/03/2023, 14:03 - ', '18/03/2023, 14:03 - ', '18/03/2023, 14:03 - ', '18/03/2023, 15:25 - ', '18/03/2023, 16:03 - ', '18/03/2023, 16:03 - ', '18/03/2023, 16:10 - ', '18/03/2023, 16:10 - ', '18/03/2023, 16:11 - ', '18/03/2023, 16:11 - ', '18/03/2023, 16:11 - ', '18/03/2023, 16:11 - ', '18/03/2023, 16:11 - ', '18/03/2023, 16:11 - ', '18/03/2023, 16:11 - ', '18/03/2023, 16:11 - ', '18/03/2023, 16:11 - ', '18/03/2023, 16:11 - ', '18/03/2023, 16:12 - ', '18/03/2023, 16:52 - ', '18/03/2023, 16:52 - ', '18/03/2023, 18:07 - ', '18/03/2023, 18:09 - ', '18/03/2023, 18:37 - ', '18/03/2023, 19:07 - ', '18/03/2023, 19:07 - ', '18/03/2023, 19:12 - ', '18/03/2023, 19:29 - ', '18/03/2023, 19:29 - ', '18/03/2023, 19:31 - ', '18/03/2023, 19:31 - ', '18/03/2023, 19:32 - ', '18/03/2023, 19:32 - ', '18/03/2023, 19:32 - ', '18/03/2023, 19:32 - ', '18/03/2023, 20:47 - ', '18/03/2023, 20:47 - ', '18/03/2023, 20:51 - ', '18/03/2023, 20:51 - ', '18/03/2023, 20:54 - ', '18/03/2023, 20:55 - ', '19/03/2023, 09:29 - ', '19/03/2023, 09:29 - ', '19/03/2023, 09:38 - ', '19/03/2023, 09:38 - ', '19/03/2023, 09:38 - ', '19/03/2023, 10:36 - ', '19/03/2023, 10:36 - ', '19/03/2023, 11:38 - ', '19/03/2023, 12:15 - ', '19/03/2023, 12:17 - ', '19/03/2023, 12:17 - ', '19/03/2023, 12:17 - ', '19/03/2023, 12:17 - ', '19/03/2023, 12:18 - ', '19/03/2023, 12:18 - ', '19/03/2023, 12:18 - ', '19/03/2023, 12:18 - ', '19/03/2023, 12:35 - ', '19/03/2023, 12:50 - ', '19/03/2023, 12:50 - ', '19/03/2023, 12:50 - ', '19/03/2023, 12:50 - ', '19/03/2023, 14:14 - ', '19/03/2023, 15:28 - ', '19/03/2023, 15:38 - ', '19/03/2023, 16:04 - ', '19/03/2023, 16:30 - ', '19/03/2023, 16:22 - ', '19/03/2023, 17:06 - ', '19/03/2023, 17:06 - ', '19/03/2023, 17:06 - ', '19/03/2023, 17:07 - ', '19/03/2023, 17:07 - ', '19/03/2023, 17:07 - ', '19/03/2023, 17:08 - ', '19/03/2023, 17:26 - ', '19/03/2023, 17:27 - ', '19/03/2023, 17:27 - ', '19/03/2023, 17:27 - ', '19/03/2023, 17:27 - ', '19/03/2023, 17:27 - ', '19/03/2023, 17:43 - ', '19/03/2023, 17:43 - ', '19/03/2023, 17:44 - ', '19/03/2023, 17:57 - ', '19/03/2023, 18:12 - ', '19/03/2023, 18:35 - ', '19/03/2023, 19:29 - ', '19/03/2023, 20:15 - ', '19/03/2023, 20:35 - ', '19/03/2023, 20:35 - ', '19/03/2023, 20:35 - ', '19/03/2023, 20:35 - ', '19/03/2023, 22:42 - ', '19/03/2023, 22:42 - ', '19/03/2023, 22:42 - ', '19/03/2023, 23:01 - ', '19/03/2023, 23:01 - ', '19/03/2023, 23:01 - ', '19/03/2023, 23:11 - ', '19/03/2023, 23:11 - ', '19/03/2023, 23:49 - ', '20/03/2023, 07:13 - ', '20/03/2023, 07:13 - ', '20/03/2023, 07:46 - ', '20/03/2023, 08:41 - ', '20/03/2023, 08:41 - ', '20/03/2023, 08:41 - ', '20/03/2023, 08:42 - ', '20/03/2023, 08:42 - ', '20/03/2023, 08:42 - ', '20/03/2023, 08:53 - ', '20/03/2023, 08:53 - ', '20/03/2023, 08:54 - ', '20/03/2023, 08:57 - ', '20/03/2023, 08:57 - ', '20/03/2023, 08:57 - ', '20/03/2023, 09:00 - ', '20/03/2023, 09:22 - ', '20/03/2023, 09:22 - ', '20/03/2023, 09:23 - ', '20/03/2023, 09:30 - ', '20/03/2023, 09:30 - ', '20/03/2023, 09:30 - ', '20/03/2023, 09:30 - ', '20/03/2023, 09:31 - ', '20/03/2023, 09:31 - ', '20/03/2023, 09:36 - ', '20/03/2023, 13:43 - ', '20/03/

In [7]:
df = pd.DataFrame({'user_message': message, 'message_date': dates})

# Converting message_date type
df['message_date'] = pd.to_datetime(
    df['message_date'], format='%d/%m/%Y, %H:%M - ')

df.rename(columns={"message_date": "date"}, inplace=True)
df.head()

                                        user_message                date
0  Messages and calls are end-to-end encrypted. N... 2023-01-08 10:29:00
1                               FHWS Aniket 🇩🇪: Hi\n 2023-01-28 07:48:00
2                      FHWS Aniket 🇩🇪: Aniket here\n 2023-01-28 07:48:00
3  FHWS Aniket 🇩🇪: Did you book an appointment at... 2023-01-28 07:48:00
4  FHWS Aniket 🇩🇪: Whtas your name and where are ... 2023-01-28 07:49:00

In [8]:
df.shape

(3290, 2)

In [9]:
user = []
messages = []
for message in df["user_message"]:
    entry = re.split("([\w\W]+?):\s", message)
    if entry[1:]:
        user.append(entry[1])
        messages.append(entry[2])
    else:
        user.append("group_notification")
        messages.append(entry[0])

df["user"] = user
df["message"] = messages
df.drop(columns=["user_message"], inplace=True)

df.head()

,date,user,message
0,2023-01-08 10:29:00,group_notification,Messages and calls are end-to-end encrypted. N...
1,2023-01-28 07:48:00,FHWS Aniket 🇩🇪,Hi\n
2,2023-01-28 07:48:00,FHWS Aniket 🇩🇪,Aniket here\n
3,2023-01-28 07:48:00,FHWS Aniket 🇩🇪,Did you book an appointment at consulate or vi...
4,2023-01-28 07:49:00,FHWS Aniket 🇩🇪,Whtas your name and where are you from?\n

In [10]:
df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month_name()
df["day"] = df["date"].dt.day
df["hour"] = df["date"].dt.hour
df["minute"] = df["date"].dt.minute
df.head()

,date,user,message,year,month,day,hour,minute
0,2023-01-08 10:29:00,group_notification,Messages and calls are end-to-end encrypted. N...,2023,January,8,10,29
1,2023-01-28 07:48:00,FHWS Aniket 🇩🇪,Hi\n,2023,January,28,7,48
2,2023-01-28 07:48:00,FHWS Aniket 🇩🇪,Aniket here\n,2023,January,28,7,48
3,2023-01-28 07:48:00,FHWS Aniket 🇩🇪,Did you book an appointment at consulate or vi...,2023,January,28,7,48
4,2023-01-28 07:49:00,FHWS Aniket 🇩🇪,Whtas your name and where are you from?\n,2023,January,28,7,49